1-module completed
js-tasks-ru/jsbasic-20230428_mihail04 pull request #2
Opened 2023-05-03 11:17 UTC by Icemore298

1-5 task

2023-05-03 11:17 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-05-03 11:46 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-05-03 13:50 UTC, SinimaWath requested changes

2023-05-03 13:50 UTC, SinimaWath commented on 1-module/2-task/index.js
> +  }
Давай тут используем операторы &&, ||: `return name !== null && ... && ...`

2023-05-03 13:50 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  }
`return newStr.indexOf('1xbet')>=0 || newStr.indexOf('xxx')>=0`, так как операция возвращает boolean

2023-05-04 05:35 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-05-04 09:16 UTC, SinimaWath approved these changes

2023-05-04 09:16 UTC, merged